// Function App (Flex Consumption) + App Service Plan + Managed Identity
// Naming conventions: func-, asp-, id-

@description('Azure region for all resources.')
param location string

@description('Environment abbreviation.')
@allowed(['dev', 'prod'])
param env string

@description('Storage account name.')
param storageAccountName string

@description('Storage connection string for table access and deployment packages.')
param storageConnectionString string

@description('ntfy topic for birthday notifications.')
param ntfyTopic string

@description('Number of days in advance to send an upcoming birthday reminder.')
param upcomingReminderDays int

@description('Resource tags.')
param tags object

var functionAppName = 'func-br-${env}-${location}'
var aspName = 'asp-br-${env}-${location}'
var identityName = 'id-br-${env}-${location}-01'
var deploymentContainerName = 'app-package-${functionAppName}'

// ── Managed Identity ──────────────────────────────────────────────────────────

resource identity 'Microsoft.ManagedIdentity/userAssignedIdentities@2018-11-30' = {
  name: identityName
  location: location
}

// ── App Service Plan (Flex Consumption) ───────────────────────────────────────

resource asp 'Microsoft.Web/serverfarms@2024-11-01' = {
  name: aspName
  location: location
  tags: tags
  kind: 'linux'
  sku: {
    tier: 'FlexConsumption'
    name: 'FC1'
  }
  properties: {
    reserved: true
  }
}

// ── Deployment Blob Container ─────────────────────────────────────────────────

resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2022-05-01' = {
  name: '${storageAccountName}/default'
}

resource deploymentContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2022-05-01' = {
  name: '${storageAccountName}/default/${deploymentContainerName}'
  dependsOn: [blobService]
}

// ── Role Assignment: Storage Blob Data Owner ──────────────────────────────────

var storageBlobDataOwnerRoleId = 'b7e6dc6d-f1e8-4753-8033-0f276bb0955b'

resource storageAccount 'Microsoft.Storage/storageAccounts@2022-05-01' existing = {
  name: storageAccountName
}

resource roleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(subscription().id, resourceGroup().id, functionAppName, storageBlobDataOwnerRoleId)
  scope: storageAccount
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', storageBlobDataOwnerRoleId)
    principalId: identity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// ── Function App ──────────────────────────────────────────────────────────────

resource functionApp 'Microsoft.Web/sites@2024-04-01' = {
  name: functionAppName
  location: location
  tags: tags
  kind: 'functionapp,linux'
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${identity.id}': {}
    }
  }
  properties: {
    serverFarmId: asp.id
    httpsOnly: true
    clientAffinityEnabled: false
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    siteConfig: {
      appSettings: [
        {
          name: 'DEPLOYMENT_STORAGE_CONNECTION_STRING'
          value: storageConnectionString
        }
        {
          name: 'AzureWebJobsStorage__credential'
          value: 'managedidentity'
        }
        {
          name: 'AzureWebJobsStorage__clientId'
          value: identity.properties.clientId
        }
        {
          name: 'AzureWebJobsStorage__blobServiceUri'
          value: 'https://${storageAccountName}.blob.core.windows.net'
        }
        {
          name: 'AzureWebJobsStorage__queueServiceUri'
          value: 'https://${storageAccountName}.queue.core.windows.net'
        }
        {
          name: 'AzureWebJobsStorage__tableServiceUri'
          value: 'https://${storageAccountName}.table.core.windows.net'
        }
        {
          name: 'STORAGE_CONNECTION_STRING'
          value: storageConnectionString
        }
        {
          name: 'NTFY_TOPIC'
          value: ntfyTopic
        }
        {
          name: 'UPCOMING_REMINDER_DAYS'
          value: string(upcomingReminderDays)
        }
        {
          name: 'WEBSITE_TIME_ZONE'
          value: 'Eastern Standard Time'
        }
      ]
    }
    functionAppConfig: {
      deployment: {
        storage: {
          type: 'blobContainer'
          value: 'https://${storageAccountName}.blob.core.windows.net/${deploymentContainerName}'
          authentication: {
            type: 'StorageAccountConnectionString'
            storageAccountConnectionStringName: 'DEPLOYMENT_STORAGE_CONNECTION_STRING'
          }
        }
      }
      scaleAndConcurrency: {
        maximumInstanceCount: 100
        instanceMemoryMB: 512
      }
      runtime: {
        name: 'python'
        version: '3.10'
      }
    }
  }
  dependsOn: [deploymentContainer, roleAssignment]
}

// ── Publishing Credentials Policies ──────────────────────────────────────────

resource scmPolicy 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2022-09-01' = {
  name: 'scm'
  parent: functionApp
  properties: {
    allow: false
  }
}

resource ftpPolicy 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2022-09-01' = {
  name: 'ftp'
  parent: functionApp
  properties: {
    allow: false
  }
}

// ── Outputs ──────────────────────────────────────────────────────────────────

output functionAppName string = functionApp.name
